### ISSUE TITLE
sir how to fix dc checker to wake up?

### ISSUE THREAD

**Issue by adhafaiq** [norecha/pokubot#14] opened 2015-01-29 10:58 UTC
![faiq902](https://cloud.githubusercontent.com/assets/10744976/5956419/c3dbecc0-a7e8-11e4-89bb-5eb2d3e0c017.png)

**Comment by adhafaiq** [comment] 2015-01-29 11:05
![bad_base_1422529355826](https://cloud.githubusercontent.com/assets/10744976/5956539/cf622be4-a7e9-11e4-95a2-fe557f2afa36.png)
![bad_base_1422529435810](https://cloud.githubusercontent.com/assets/10744976/5956540/d07540ac-a7e9-11e4-8bb7-9bc788643dfa.png)
this is the bug

**Comment by adhafaiq** [comment] 2015-01-29 12:06
sir, why when i found a base with dark elixer its automatically say "waiting for the dc checker to wake me up"? Help me pls...

**Comment by norecha** [comment] 2015-01-29 13:05
Duplicate of #11

**Closed by norecha** 2015-01-29 13:05 UTC

**Comment by mmajid** [comment] 2015-01-29 13:09
Yeah sure i can. So far i am able to know the issue occurs when running UI but when i run your console version it works fine. I did not try to figure out where is the problem because it was working fine for me on console botlauncher if u want my help i can look for u what is the problem.

--- Original Message ---

**Comment by adhafaiq** [comment] 2015-01-29 17:17
hi sir thanks for the reply. I'm townhall 6 and don't have dark elixir storage and when i found a base that have dark elixir, it suddenly stop. Do i need to have dark elixir storage to make this bot works? 

     On Thursday, January 29, 2015 9:10 PM, mmajid <notifications@github.com> wrote:
   

 Yeah sure i can. So far i am able to know the issue occurs when running UI but when i run your console version it works fine. I did not try to figure out where is the problem because it was working fine for me on console botlauncher if u want my help i can look for u what is the problem.

--- Original Message ---

**Comment by norecha** [comment] 2015-01-29 17:22
@adhafaiq 
I sent you a new .jar file to your email, try with that

**Comment by hyuda** [comment] 2015-01-30 04:59
Hi norecha
Ca i get email too because i have same problem with adhafaiq
My email: dk_kurniawan@ymail.com

Thanks

**Comment by salimovitch** [comment] 2015-01-30 13:42
Please help me i have the exact same probleme, and now it stops at (state search a match) and then it doesn't attaque or click to search next village to attaque.

**Comment by salimovitch** [comment] 2015-01-30 13:43
my email : salimo12@hotmail.fr
pls send me some instructions, do we have to put the .jar file in a specefic folder or destination ?

**Comment by norecha** [comment] 2015-01-30 13:43
Make game language English.

**Comment by salimovitch** [comment] 2015-01-30 14:42
i did it, it is in english, 
but when it found a village with dark elexir (village with existing dark elixir) it stops searching and write error 

Date: Fri, 30 Jan 2015 05:43:24 -0800

**Comment by salimovitch** [comment] 2015-01-30 14:44
ERROR ff83782b still got this error when it search and find village with dark elixir, please help or send me and other version thank you 
Date: Fri, 30 Jan 2015 05:43:24 -0800

**Comment by norecha** [comment] 2015-01-30 14:45
check your email

**Comment by salimovitch** [comment] 2015-01-30 14:47
ok thanks i will try this and reply to you 
Date: Fri, 30 Jan 2015 06:45:27 -0800

**Comment by salimovitch** [comment] 2015-01-30 15:12
I've tried it, it is working perfectly thanks a lot man, good work and god bless u :)  

Date: Fri, 30 Jan 2015 06:45:27 -0800
